name:                mrun-crypt
version:             1.0.0
github:              "ruzen42/mcrypt"
license:             MIT 
maintainer:          "ruzen@tuta.io"

extra-source-files:
- README.md
- CHANGELOG.md

category:            Cryptography 

description:         Please see the README on GitHub at <https://github.com/ruzen42/mcrypt#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - random
  - binary
  - bytestring
  - filepath
  - directory
  - blake3
  - ram
  c-sources:
  - cbits/oqs_shim.c
  include-dirs:
  - cbits 
  extra-libraries:
  - oqs 

executables:
  mcrypt:
    main:                Main.hs
    source-dirs:         mcrypt
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mrun-crypt
    - optparse-applicative
  mkey:
    main:                Main.hs
    source-dirs:         mkey 
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mrun-crypt
    - optparse-applicative

tests:
  mrun-crypt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mrun-crypt
